apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
spec:
  ipFamily: IPv4
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
  externalIPs:
    - 10.0.0.6
  selector:
    app: botmasterzzz-telegram